export const planes = [
  {
    id: 4,
    id_flow: "plan_prueba",
    nombre_plan: "Plan Básico",
    precio_plan: 1,
    precio_plan_soles: 3.6,
    titulo: " Paga por 1 mes",
    descripcion: "*30 días de contenido exclusivo",
    color_card: "#FFEE97",
    color_principal: "#FFE251",
    color_text: "#8A8A8A",
    ruta_img: "/planes/planB.png",
    paypal_id: "P-3U578176AR727953NNGSZ7XA",
  },
  {
    id: 2,
    id_flow: "plan_prueba",
    nombre_plan: "Plan Estándar",
    precio_plan: 27,
    precio_plan_soles: 99,
    titulo: " Paga por 6 meses y ahorra 10%",
    descripcion: "*precio regular $30USD",
    color_card: "#C3F3F3",
    color_principal: "#68E1E0",
    color_text: "#8A8A8A",
    ruta_img: "/planes/planE.png",
    paypal_id: "P-3U578176AR727953NNGSZ7XA",
  },
  {
    id: 3,
    id_flow: "plan_prueba",
    nombre_plan: "Plan Pro Crafter",
    precio_plan: 55,
    precio_plan_soles: 192,
    titulo: "Paga una vez al año",
    descripcion: "*precio regular $60USD",
    color_card: "#FFB4DF",
    color_principal: "#FC68B9",
    color_text: "#ffffff",
    ruta_img: "/planes/planPro.png",
    paypal_id: "P-3U578176AR727953NNGSZ7XA",
  },
];
